"""add table

Revision ID: 051357adcc5d
Revises: b67f1e3661fe
Create Date: 2024-10-09 20:51:04.952867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051357adcc5d'
down_revision = 'b67f1e3661fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surfboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('length', sa.String(length=80), nullable=True),
    sa.Column('width', sa.String(length=80), nullable=True),
    sa.Column('thickness', sa.String(length=80), nullable=True),
    sa.Column('volume', sa.String(length=80), nullable=True),
    sa.Column('image_filename', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('surfboard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surfboard_id'], ['surfboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('surfboard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surfboard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('length', sa.VARCHAR(length=80), nullable=True),
    sa.Column('width', sa.VARCHAR(length=80), nullable=True),
    sa.Column('thickness', sa.VARCHAR(length=80), nullable=True),
    sa.Column('volume', sa.VARCHAR(length=80), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('reviews')
    op.drop_table('surfboards')
    # ### end Alembic commands ###
