"""Add primary key column

Revision ID: 1efa1c8756d0
Revises: 9bd49ec082f0
Create Date: 2024-10-05 13:14:17.678954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efa1c8756d0'
down_revision = '9bd49ec082f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surfboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surfboard_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surfboard', schema=None) as batch_op:
        batch_op.drop_column('surfboard_id')

    # ### end Alembic commands ###
