"""image_field added

Revision ID: 9bd49ec082f0
Revises: f75b8bf6a2e4
Create Date: 2024-10-04 19:34:29.676971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd49ec082f0'
down_revision = 'f75b8bf6a2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surfboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=80), nullable=False))
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('thickness',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surfboard', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.String(length=80),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('thickness',
               existing_type=sa.String(length=80),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.String(length=80),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.String(length=80),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
