"""Add surfboard_id

Revision ID: b67f1e3661fe
Revises: 1efa1c8756d0
Create Date: 2024-10-05 13:30:03.672187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67f1e3661fe'
down_revision = '1efa1c8756d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surfboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('surfboard_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surfboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surfboard_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
